global using System.Collections.Immutable;
global using Microsoft.Extensions.DependencyInjection;
global using Microsoft.Extensions.Hosting;
global using Microsoft.Extensions.Localization;
global using Microsoft.Extensions.Logging;
global using Microsoft.Extensions.Options;
global using UnoApp13.DataContracts;
global using UnoApp13.DataContracts.Serialization;
global using UnoApp13.Models;
global using UnoApp13.Presentation;
global using UnoApp13.Services.Caching;
global using UnoApp13.Services.Endpoints;
global using ApplicationExecutionState = Windows.ApplicationModel.Activation.ApplicationExecutionState;
